---
# title: "3xTg-AD-serial-reversal"
execute:
  echo: false
  warning: false
format:
    pdf:
        include-in-header: 
            text: |
                \usepackage{fancyhdr}
        include-before-body:
            text: |
                \pagestyle{fancy}
                \fancyhead[L]{Serial Reversal in 3xTg-AD Mice}
                \fancyhead[R]{\today}
                \fancyfoot[C]{\thepage}
---

```{r}
#### Load libraries ----------------------------------------------------
library(here)
library(janitor)
library(tidyverse)
library(MuMIn)
    options(na.action = "na.fail")
library(lme4)
library(knitr)
    options(knitr.kable.NA = '')
library(kableExtra)

#### Read and wrangle data ---------------------------------------------

# Genotypes data

geno <- read_csv(here("data", "geno clean.csv"),
                 col_types = "cffDDdd") %>% 
    mutate(sex = case_when(
            sex == "f" ~ "Female",
            sex == "m" ~ "Male"),
        sex = as.factor(sex),
        geno = case_when(
            geno == "tg" ~ "3xTg-AD",
            geno == "wt" ~ "B6129"),
        geno = as.factor(geno)) %>% 
    clean_names()

# Manual data

manual_files <- list.files(here("data", "csvs"),
                           pattern = "\\.csv",
                           full.names = TRUE)

manual_data <- manual_files %>% 
    map_dfr(read_csv,
            col_types = "cccdddddl") %>% 
    clean_names() %>% 
    filter(!exclude) %>% 
    mutate(rev = rev == "yes",
           retest = str_to_lower(op) == "retest") %>% 
    rename(animal = mouse) %>% 
    select(-exclude)

# Auto data

auto_files <- list.files(here("data", "auto"),
                         pattern = "\\.csv",
                         full.names = TRUE)

auto_data <- auto_files %>% 
    map_dfr(read_csv,
            col_types = "ccddccdddddccdddddccldlld",
            comment = "#") %>% 
    clean_names() %>% 
    mutate(animal = case_when(
            animal == "1297" ~ "1927",
            TRUE ~ animal),
           op = str_extract(study_name,
                            "[:digit:]+"),
           rev = str_detect(study_name,
                            "REV"),
           retest = str_detect(study_name,
                               "RETEST")) %>% 
    group_by(animal, date, study_name, block, op, rev, retest) %>% 
    summarise(hit = sum(correct[trial_type == "P"], na.rm = TRUE),
              p_trials = sum(trial_type[!ss] == "P"),
              cr = sum(correct[trial_type == "N"], na.rm = TRUE),
              n_trials = sum(trial_type[!ss] == "N")) %>% 
    ungroup() %>% 
    select(-date, -study_name)

# Combine manual and auto data, summarize and add genotypes

dat <- bind_rows(manual_data, auto_data) %>% 
    group_by(animal, op, rev, retest) %>% 
    summarise(across(hit:n_trials,
                     ~ sum(.x))) %>% 
    mutate(errors = (p_trials + n_trials) - (hit + cr),
           op = case_when(
               op %in% 0:18 ~ as.numeric(op)
           ),
           rev = as.factor(rev),
           retest = as.factor(retest)) %>% 
    left_join(geno,
              by = c("animal" = "mouse")) %>% 
    ungroup()

```

```{r}
#### Check for incomplete data ------------------------------------
incomplete_mice <- dat %>% 
    group_by(animal, rev, retest) %>% 
    summarise(max_op = max(op),
              min_op = min(op)) %>% 
    filter(max_op != 18, retest == FALSE) %>% 
    pull(animal) %>% 
    unique()

# Drop mice with incomplete data
dat <- dat %>% 
    filter(!(animal %in% incomplete_mice))
```

# Subjects

```{r}
#### Demographics ---------------------------------------------
geno %>% 
    filter(!(mouse %in% incomplete_mice)) %>% 
    group_by(geno, sex) %>% 
    summarise(mean_age = mean(days),
              min_age = min(days),
              max_age = max(days),
              n = length(days)) %>% 
    kable(format = "latex",
          col.names = c("Genotype", "Sex", "Mean age (days)",
                        "Minimum age (days)", "Maximum age (days)", "N"),
          caption = "Demographics of mice tested.",
          digits = 2)

```

# Discrimination

```{r}
#| fig-cap: "Errors (±95% CI) made by the mice at on each odour pair during the discrimination stages."

disc_dat <- dat %>% 
    filter(retest == FALSE, 
           rev == FALSE)

disc_dat %>% 
    ggplot(aes(x = op,
               y = errors,
               colour = geno)) +
    geom_point(alpha = .2,
               shape = 20) + 
    stat_summary(fun.data = "mean_cl_boot") +
    geom_smooth(se = FALSE) +
    theme_classic() +
    theme(legend.title = element_blank(),
          legend.position = c(.9, .9)) +
    labs(x = "Odour pair",
         y = "Errors")
    
```

```{r}
#### Tests -------------------------------------------------------

# Discrimination

disc_fm <- lmer(errors ~ op * sex * geno + (1|animal),
                data = disc_dat,
                REML = FALSE)

disc_model_table <- dredge(disc_fm,
       fixed = "op")

disc_model_table %>% 
    kable(caption = "AICc model table for discrimination.",
          digits = 2,
          row.names = FALSE) %>% 
    kable_styling(latex_options = c("scale_down"))
```

# Reversal

```{r}
#| fig-cap: "Errors (±95% CI) made by the mice at on each odour pair during the reversal stages."

rev_dat <- dat %>% 
    filter(retest == FALSE, 
           rev == TRUE)

rev_dat %>% 
    ggplot(aes(x = op,
               y = errors,
               colour = geno)) +
    geom_point(alpha = .2,
               shape = 20) + 
    stat_summary(fun.data = "mean_cl_boot") +
    geom_smooth(se = FALSE) +
    theme_classic() +
    theme(legend.title = element_blank(),
          legend.position = c(.9, .9)) +
    labs(x = "Odour pair",
         y = "Errors")
```


```{r}
# Reversal
rev_fm <- lmer(errors ~ op * sex * geno + (1|animal),
               data = rev_dat,
               REML = FALSE)

rev_model_table <- dredge(rev_fm,
       fixed = "op")

rev_model_table %>% 
    kable(caption = "AICc model table for reversal.",
          digits = 2,
          row.names = FALSE) %>% 
    kable_styling(latex_options = c("scale_down"))
```
